--- 
- name: Syslog
  hosts: NetworkDevices
  gather_facts: false

  tasks: 
  - name: Configure logging host
    cisco.ios.ios_config:
      lines:
        - logging host 10.0.40.2
        - logging trap debugging
    tags: Syslog