name: Branch-B
topology:
  kinds:
    ceos:
      image: ceos:4.34.1F
    cisco_iol:
      image: vrnetlab/cisco_iol:17.18.02

  nodes:
    r2:
      kind: cisco_iol
      startup-config: r2.txt.partial
    spine:
      kind: ceos
      startup-config: spine.txt.partial
    leaf:
      kind: ceos
      startup-config: leaf.txt.partial
    gns3-br:
      kind: bridge

  links:
    - endpoints: ["r2:e0/1", "gns3-br:eth0"]
    - endpoints: ["r2:e0/2", "spine:eth1"]
    - endpoints: ["spine:eth2", "leaf:eth1"]
    # - endpoints: ["leaf:eth2", "gns3-br:eth1"]