export { ITOverview, ITDevelopment, ITInfrastructure, ITAutomation, ITMonitoring } from './pages-it.jsx'
export { ITIncidents, ITDeployments, ITTickets, ITSubscribers } from './pages-it2.jsx'
export { ITFabric, ITWorkloads } from './pages-it3.jsx'
export { HROverview, HRDirectory, HRRecruitment, HRLeave, HRPayroll, HRExpenses, HRDocuments, HRPolicies, HROKRs } from './pages-hr.jsx'
export { BizOverview, BizCustomers, BizBilling, BizInvoices, BizRevenue, BizPipeline } from './pages-biz.jsx'
export { MailPage, AnnouncementsPage, HelpdeskPage, SelfServicePage, FilesPage, DeptDocumentsPage } from './pages-shared.jsx'
export { SettingsPage } from './pages-settings.jsx'
export { LoginPage }   from './LoginPage.jsx'
export { AdminPanel }  from './AdminPanel.jsx'
