import nodemailer from 'nodemailer'
import { existsSync, readdirSync, readFileSync, renameSync, writeFileSync, mkdirSync } from 'fs'
import { join } from 'path'

const MAIL_DOMAIN = process.env.MAIL_DOMAIN || 'pfe2627.xyz'
const MAIL_BASE   = process.env.MAIL_BASE   || '/var/mail/vmail'
const FOLDER_DIRS = { inbox: ['new','cur'], sent: ['sent'], draft: ['tmp'], star: ['star'], arch: ['arch'] }

function maildirRoot(c) { return join(MAIL_BASE, MAIL_DOMAIN, (c?.user||'').split('@')[0], 'Maildir') }
function ensureDir(p) { try { mkdirSync(p,{recursive:true}) } catch {} }
function newFn() { return `${Math.floor(Date.now()/1000)}.${Math.random().toString(36).slice(2,10)}.${MAIL_DOMAIN}` }
const toUid=f=>Buffer.from(f).toString('base64url'), fromUid=u=>Buffer.from(u,'base64url').toString('utf8')
function decHdr(s=''){return s.replace(/=\?([^?]+)\?(B|Q)\?([^?]+)\?=/gi,(_,_c,e,t)=>{try{return e.toUpperCase()==='B'?Buffer.from(t,'base64').toString('utf8'):t.replace(/_/g,' ').replace(/=([0-9A-F]{2})/gi,(_,h)=>String.fromCharCode(parseInt(h,16)))}catch{return t}})}
function parseAddr(s=''){const m=s.match(/^(.+?)\s*<([^>]+)>$/);return m?{name:m[1].trim().replace(/^"|"$/g,''),email:m[2].trim()}:{name:s.trim(),email:s.trim()}}
function parseMail(buf){const str=buf.toString('utf8'),sep=str.indexOf('\n\n'),hStr=sep>=0?str.slice(0,sep):str,bStr=sep>=0?str.slice(sep+2):'';const h={};let k=null;for(const l of hStr.split('\n')){if(/^\s/.test(l)&&k){h[k]+=' '+l.trim();continue}const m=l.match(/^([\w-]+)\s*:\s*(.*)/);if(m){k=m[1].toLowerCase();h[k]=m[2].trim()}}let body=bStr;const enc=(h['content-transfer-encoding']||'').toLowerCase();if(enc==='base64')body=Buffer.from(bStr.replace(/\s/g,''),'base64').toString('utf8');else if(enc==='quoted-printable')body=bStr.replace(/=\r?\n/g,'').replace(/=([0-9A-F]{2})/gi,(_,hx)=>String.fromCharCode(parseInt(hx,16)));return{headers:h,body,isHtml:(h['content-type']||'').includes('text/html')}}
function fmtT(ds){const d=new Date(ds||0);if(isNaN(d))return '';const now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate()),yst=new Date(+today-86400000),day=new Date(d.getFullYear(),d.getMonth(),d.getDate());if(day>=today)return d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});if(day>=yst)return 'Yesterday';return d.toLocaleDateString([],{month:'short',day:'numeric'})}
function fileToMsg(fp,fn,fid,unread,full=false){try{const{headers:h,body,isHtml}=parseMail(readFileSync(fp)),from=parseAddr(decHdr(h.from||'')),text=isHtml?body.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim():body.trim(),htmlBody=isHtml?body:`<pre style="white-space:pre-wrap;font-family:inherit;font-size:13.5px">${body.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}</pre>`;return{uid:toUid(fn),folder:fid,from:from.name||from.email,fromEmail:from.email,subject:decHdr(h.subject||'(no subject)'),preview:text.slice(0,120),...(full?{body:htmlBody}:{}),time:fmtT(h.date),date:h.date||'',unread,starred:false,labels:[]}}catch{return null}}

export async function listMessages(fid,creds){if(!creds?.user)return[];const root=maildirRoot(creds),dirs=FOLDER_DIRS[fid]||['cur'],msgs=[];for(const dir of dirs){const dp=join(root,dir);ensureDir(dp);try{for(const f of readdirSync(dp)){const m=fileToMsg(join(dp,f),f,fid,dir==='new');if(m)msgs.push(m)}}catch{}}return msgs.sort((a,b)=>new Date(b.date)-new Date(a.date))}
export async function getMessage(fid,uid,creds){if(!creds?.user)return null;const root=maildirRoot(creds),fn=fromUid(uid);for(const dir of(FOLDER_DIRS[fid]||['cur'])){const p=join(root,dir,fn);if(existsSync(p))return fileToMsg(p,fn,fid,dir==='new',true)}return null}
export async function markRead(fid,uid,read,creds){if(!creds?.user||fid!=='inbox')return true;const root=maildirRoot(creds),fn=fromUid(uid),np=join(root,'new',fn),cp=join(root,'cur',fn);if(read&&existsSync(np)){ensureDir(join(root,'cur'));renameSync(np,cp)}if(!read&&existsSync(cp)){ensureDir(join(root,'new'));renameSync(cp,np)}return true}
export async function deleteMessage(fid,uid,creds){if(!creds?.user)return false;const root=maildirRoot(creds),fn=fromUid(uid);for(const dir of(FOLDER_DIRS[fid]||['cur'])){const src=join(root,dir,fn);if(existsSync(src)){const ad=join(root,'arch');ensureDir(ad);renameSync(src,join(ad,fn));return true}}return false}
export async function sendMessage({from,to,subject,body},creds){const t=nodemailer.createTransport({host:process.env.SMTP_HOST||'localhost',port:Number(process.env.SMTP_PORT)||587,secure:process.env.SMTP_SECURE==='true',...(creds?{auth:{user:creds.user,pass:creds.pass}}:{}),tls:{rejectUnauthorized:false}});const info=await t.sendMail({from,to,subject,html:body,text:body.replace(/<[^>]+>/g,'')});try{const se=(from.match(/<(.+)>/)||[,from])[1],sd=join(maildirRoot({user:se}),'sent');ensureDir(sd);const raw=[`From: ${from}`,`To: ${to}`,`Subject: ${subject}`,`Date: ${new Date().toUTCString()}`,`Message-ID: <${info.messageId}>`,`Content-Type: text/html; charset=utf-8`,`Content-Transfer-Encoding: 8bit`,'',body].join('\n');writeFileSync(join(sd,newFn()),raw,'utf8')}catch{}return{messageId:info.messageId}}
