-- /etc/dovecot/dovecot.conf --
# Dovecot main configuration file for IMAP service
!include_try /usr/share/dovecot/protocols.d/*.protocol

dict {
  #quota = mysql:/etc/dovecot/dovecot-dict-sql.conf.ext
}

!include conf.d/*.conf
!include_try local.conf
protocols = imap
